### PR TITLE
Optimization and bug fix

### LINKED ISSUE #28: v1.0.11 Not working in Firefox
Hey - I was using the v1.0.10 release and it was working fine but the new version is broken in Firefox (works in chrome).

I get 'ReferenceError: event is not defined' when clicking on the card

Happens even when I try the demo flip at the top of http://nnattawat.github.io/flip/

### PR DESCRIPTION
**Pull request by JemarJones**
Optimized the callback code very slightly and fixed #28.

### CODE REVIEW

**Comment by Download** [comment]
Hi Jemar, to be able to build you need to install Node JS. Then install Grunt (which is a build tool) and then run `grunt` in the main project folder. Have a look at the section [Development](https://github.com/nnattawat/flip#development).

To make a release:

* Update version numbers in package.json and bower.json
* Update version numbers in README.md
* Add a small change log to README.md
* Use Grunt to build the dist files
* Check everything in and push to the repo
* Then, inside Github, on tab [Releases](https://github.com/nnattawat/flip/releases), press the button `Draft a new release`
* Fill in the new version number for the tag
* Add a title and a description (I copy this from README.md and edit a bit)
* Upload these 3 files to the release:
   * `dist/jquery.flip.js`
   * `dist/jquery.flip.min.js`
   * `dist/jquery.flip.min.js.map`
* Press the `Publish` button and you're done!

**Comment by Download** [comment]
Manually merged and applied. Is in release v1.0.12.

**Comment by JemarJones** [comment]
Thanks! Can I do all/any of that on a branch before creating a PR without bower and the main release being updated prematurely?

**Comment by Download** [comment]
Yes I think you can... Apart from the Release in GitHub step, I'm not sure about that one.

**Comment by Download** [comment]
Oh I should add that there is a 'magic' branch called `gh-pages` that contains the site that's at https://nnattawat.github.io/flip. So you should, after the release is finish, checkout that branch and update the version numbers in the index.html that is in there. Also, if you added a nice feature, or some options, you can add docs / examples of it there. Once you push that the site gets updated automagically.

**Pull request closed without merging**
