### PR TITLE
Added value 'stop' to main function

### PR DESCRIPTION
**Pull request by Sartoric**
Added the possibility to disable element flipping.
The purpose is, mainly if triggered on hover, to keep the element flipped even if it lost focus (modal loaded on top, loader ...). It unbinds only the flipping events. 

Not sure if the setTimeout in performFlip (row 30) is useful/needed or not :-)

### CODE REVIEW

**Comment by JemarJones** [comment]
I'm not 100% clear on what functionality you're trying to add here. Is it to have an element only flip on mouseenter, but not mouseleave?  

If so why not forego the built in triggers and just do that in client code with something along the lines of:
```javascript
$(".myElement").mouseenter(function(){
    $(this).flip("toggle");
};
```

Let me know if this is what you're trying to accomplish.

**Comment by Sartoric** [comment]
Well, more or less.
I need to stop it flipping until I decide to restart it. Doing it the way you suggested, if I move the mouse over the element it's start flipping again. Using "click" as trigger could be a partial solution but I need to use "hover".
Using unbind on client code (that's what I did before) force me to unbind all the event on "hover" (or click) that's not the best practice. Maybe playing with namespaces could be a less intrusive :-) solution ? Still have to test it 

I had to apply toggle on mouseleave to let it works as I expected (element stop flip once showing back face) . Maybe flipped status is updated before "toggling" ?

**Comment by JemarJones** [comment]
Okay i see, you essentially want to remove the trigger temporarily. There is actually a branch under development currently with the feature to change the trigger. I think i could easily add the ability to pass in ```{trigger: "none"}``` there without the need for all of this extra code.

**Comment by JemarJones** [comment]
You can see the changing trigger implementation [here](https://github.com/nnattawat/flip/commit/e5429d8835bd91d2505c29de792e8294720bdc5d#diff-05d61b748d09265b390570fc3e26bdf2) if you're curious about unbinding events.

**Comment by Sartoric** [comment]
That would be useful.
I suppose that it could be enough to change the trigger (live) from "hover" to "manual" once the element is flipped .. something I've tried to do ,even if I knew it was not yet possible... and in fact everything crashed :-)

**Comment by JemarJones** [comment]
Oh yes you're right I forgot that there was already a manual option. So yea this should be should be resolved in the near future.

**Pull request closed without merging**
