### PR TITLE
Setreverse merge

### PR DESCRIPTION
**Pull request by JemarJones**

### CODE REVIEW

**Comment by Download** [comment]
Want to try to make a release of it yourself?

**Comment by JemarJones** [comment]
Sorry I was just in the middle of creating it but had to run out to head to work. Could you finish it? (I think I mightve uploaded the old files by accident)

**Comment by JemarJones** [comment]
I also already made updates the project pagebut haven't pushed those commits

**Comment by Download** [comment]
Ah the release can wait a few hours...  :)

**Comment by JemarJones** [comment]
I'm not sure how you create the source code zip and tar.gz, is there some option or is that manual?

**Comment by Download** [comment]
Git does it for you automagically  :)

**Comment by JemarJones** [comment]
Yea i just figured that out ahah. Ive now done the release and updated the page :).

**Pull request merged**
